# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Uncomment the following lines to enable RGB underglow
#CONFIG_ZMK_RGB_UNDERGLOW=y
#CONFIG_WS2812_STRIP=y
#CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=n
#CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y

# Uncomment the following line to enable the Atreyu OLED Display
CONFIG_ZMK_DISPLAY=y
#CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
#CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y

# Uncomment these two lines to add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# 用于解决 Windows 中与电池报告相关的错误
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

#休眠相关配置
# Milliseconds of inactivity before entering idle state	(10 minute)
CONFIG_ZMK_IDLE_TIMEOUT=600000
# Enable deep sleep support	
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_PM_SOFT_OFF=y
# Milliseconds of inactivity before entering deep sleep (30 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3000000
